[workspace]
channels = [
  "https://conda.modular.com/max-nightly/",
  "conda-forge",
  "https://prefix.dev/pixi-build-backends"
]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[package]
name = "pontoneer"
version = "0.6.4"
description = "Mojo library providing additional type protocol extensions for Python interop."
authors = ["Marius Seritan <39998+winding-lines@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
homepage = "https://github.com/winding-lines/pontoneer"
repository = "https://github.com/winding-lines/pontoneer"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.1.*" }

[package.build-dependencies]
mojo-compiler = "==0.26.3.0.dev2026041020"

[package.host-dependencies]
mojo = "==0.26.3.0.dev2026041020"

[package.run-dependencies]
mojo = "==0.26.3.0.dev2026041020"
python = ">=3.14.2,<3.15"

[dependencies]
mojo = "==0.26.3.0.dev2026041020"

[tasks]
fmt = "mojo format pontoneer examples tests"
build = "mojo package pontoneer -o pontoneer.mojopkg"
publish = { cmd = "find . -name 'pontoneer*.conda' | xargs pixi upload prefix --channel mojo-community" }

[feature.test.dependencies]
numpy = ">=2.4.3,<3"
python = ">=3.14.4,<3.15"

[feature.test.tasks]
build-example = { cmd = "mojo build --emit shared-lib -I . examples/columnar/mojo_module.mojo -o examples/columnar/mojo_module.so", depends-on = ["build"] }
test-example = { cmd = "python3 examples/columnar/test_module.py", depends-on = ["build-example"] }
build-test-mapping = { cmd = "mojo build --emit shared-lib -I . tests/mapping/mojo_module.mojo -o tests/mapping/mojo_module.so", depends-on = ["build"] }
test-mapping = { cmd = "python3 tests/mapping/test_module.py", depends-on = ["build-test-mapping"] }
build-test-number = { cmd = "mojo build --emit shared-lib -I . tests/number/mojo_module.mojo -o tests/number/mojo_module.so", depends-on = ["build"] }
test-number = { cmd = "python3 tests/number/test_module.py", depends-on = ["build-test-number"] }
build-test-sequence = { cmd = "mojo build --emit shared-lib -I . tests/sequence/mojo_module.mojo -o tests/sequence/mojo_module.so", depends-on = ["build"] }
test-sequence = { cmd = "python3 tests/sequence/test_module.py", depends-on = ["build-test-sequence"] }
build-test-type-protocol = { cmd = "mojo build --emit shared-lib -I . tests/type_protocol/mojo_module.mojo -o tests/type_protocol/mojo_module.so", depends-on = ["build"] }
test-type-protocol = { cmd = "python3 tests/type_protocol/test_module.py", depends-on = ["build-test-type-protocol"] }
build-test-buffer = { cmd = "mojo build --emit shared-lib -I . tests/buffer/mojo_module.mojo -o tests/buffer/mojo_module.so", depends-on = ["build"] }
test-buffer = { cmd = "python3 tests/buffer/test_module.py", depends-on = ["build-test-buffer"] }
test-all = { depends-on = ["test-example", "test-mapping", "test-number", "test-sequence", "test-type-protocol", "test-buffer"] }

[environments]
default = { solve-group = "main" }
test = { features = ["test"], solve-group = "main" }
