name: Pontoneer Test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: osx-arm64, os: macos-latest }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      MODULAR_HOME: "/home/runner/.modular"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.10
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    - name: checks
      run: pixi run fmt
    - name: tests
      run: pixi run --environment test test-all
